services:
  kerlandrierfront:
    image: kerlandrierfront
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 127.0.0.1:8090:4173
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules
    restart: unless-stopped
