services:
  kerlandrierfront:
    image: kerlandrierfront
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: ".env"
    ports:
      - 127.0.0.1:8090:5173
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules