services:
  kerlandrierapi:
    image: ghcr.io/geekks/kerlandrier_mono:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: 
      - ".env"
      - "./script/.env"
    ports:
      - 127.0.0.1:8001:8001
    volumes:
      - ./db:/api/db/
    develop: 
      watch: 
        - action: rebuild 
          path: ${PWD} 
          target: /api/
    restart: unless-stopped
volumes:
  db:
