services:
  kerlandrierapi:
    image: kerlandrierapi
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: ".env"
    ports:
      - 8001:8001
    volumes:
      - ./auth.db:/code/auth.db
